const fs = require('fs');
const path = require('path');
const { EdgeTTS } = require('node-edge-tts');

const outputDir = path.resolve(__dirname, '../public/audio/delhi');
if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir, { recursive: true });
}

// Voices
const EN_VOICE = 'en-IN-NeerjaNeural';
const HI_VOICE = 'hi-IN-SwaraNeural';

const remainingScripts = [
  {
    slug: 'jama-masjid',
    en: `Welcome to the grand Masjid-i-Jahan-Numa, universally celebrated as the Jama Masjid of Delhi, one of the largest and most venerated mosques in the Indian subcontinent. Commissioned in 1644 by the Mughal Emperor Shah Jahan following the completion of the Red Fort, this awe-inspiring architectural masterpiece took over six years and the labor of more than five thousand artisans to construct. Elevated majestically upon a lofty red sandstone natural outcrop, the mosque is approached through three monumental flight of steps that ascend to towering arched gateways. As you step onto the vast open-air red sandstone courtyard, notice that it can accommodate more than twenty-five thousand worshippers in collective prayer simultaneously. Gaze toward the western prayer hall, crowned by three magnificent bulging white marble domes intricately striped with black vertical lines, flanked by two soaring minarets rising forty meters into the sky. Crafted from vertical strips of red sandstone and brilliant white marble, these minarets provide sweeping panoramic vistas across the bustling labyrinth of Old Delhi. The central arched prayer alcove, or mihrab, is delicately adorned with Quranic inscriptions and floral motifs, offering a sacred sanctuary of profound devotion and spiritual tranquility. As the evening call to prayer echoes across the historic rooftops of Shahjahanabad, you can truly experience the living cultural heartbeat of Old Delhi. Walk softly and absorb the majesty of this sacred monument.`,
    hi: `दिल्ली की ऐतिहासिक जामा मस्जिद, यानी मस्जिद-ए-जहाँ-नुमा में आपका हार्दिक स्वागत है। यह भारत की सबसे विशाल और भव्य मस्जिदों में से एक है, जो मुग़ल वास्तुकला की पराकाष्ठा मानी जाती है। सन 1644 में सम्राट शाहजहाँ ने लाल किले के निर्माण के बाद इस महान मस्जिद की नींव रखी थी। लगभग 5000 कारीगरों की छह वर्षों की अथक मेहनत के बाद यह मस्जिद 1656 में बनकर तैयार हुई। एक ऊंचे चबूतरे पर स्थित होने के कारण यहाँ पहुँचने के लिए लाल बलुआ पत्थर की भव्य सीढ़ियाँ चढ़नी पड़ती हैं। जैसे ही आप इसके विशाल प्रांगण में प्रवेश करते हैं, आपको इसकी भव्यता का एहसास होगा, जहाँ एक साथ 25,000 से अधिक नमाज़ी एक साथ इबादत कर सकते हैं। इसके मुख्य प्रार्थना सभागार के ऊपर सफ़ेद और काले संगमरमर की धारियों वाले तीन विशाल गुंबद सुशोभित हैं। इसके दोनों ओर 40 मीटर ऊंची दो भव्य मीनारें खड़ी हैं, जो लाल बलुआ पत्थर और संगमरमर की पट्टियों से बनाई गई हैं। इन मीनारों से पुरानी दिल्ली का विहंगम दृश्य दिखाई देता है। शाम के समय जब शाहजहानाबाद की गलियों में अज़ान की मधुर आवाज़ गूँजती है, तो यहाँ का वातावरण आध्यात्मिक शांति और पवित्रता से भर जाता है। आइए, इस ऐतिहासिक और पावन धरोहर की शांति को अपने दिल में महसूस कीजिए।`
  },
  {
    slug: 'jantar-mantar',
    en: `Welcome to Jantar Mantar, an extraordinary 18th-century architectural astronomical observatory situated in the center of New Delhi. Constructed in 1724 by the scholarly astronomer king, Maharaja Jai Singh the Second of Jaipur, this unique monument was designed to compile astronomical tables and accurately predict the movements of the sun, moon, and visible planets. Dissatisfied with the inaccuracies of small brass astrolabes, Jai Singh conceived monumental stone masonry instruments whose immense scale minimized observational error. As you explore the complex, the most dominant structure you behold is the Samrat Yantra, or the Supreme Instrument. Standing twenty-seven meters high, this giant equinoctial sundial casts a shadow on two calibrated marble quadrants, allowing the observer to measure local solar time with an astonishing precision of two seconds. Nearby stands the Ram Yantra, composed of two complementary cylindrical open-topped buildings used to determine the altitude and azimuth of celestial bodies. Another remarkable device is the Jai Prakash Yantra, featuring two sunken hemispherical marble bowls that map the celestial sphere upside down, allowing astronomers to walk inside and take naked-eye planetary readings. Having survived three centuries amidst modern skyscrapers, Jantar Mantar stands as a brilliant monument to ancient Indian scientific ingenuity, mathematics, and architectural audacity. Take your time to discover the remarkable geometry etched into every masonry curve.`,
    hi: `नई दिल्ली के दिल में स्थित ऐतिहासिक खगोलीय वेधशाला जंतर मंतर में आपका स्वागत है। सन 1724 में जयपुर के विद्वान और खगोलशास्त्री महाराजा सवाई जय सिंह द्वितीय ने इस अद्भुत वेधशाला का निर्माण कराया था। उस समय के छोटे धातु के यंत्रों की गणनाओं में त्रुटियों को दूर करने के लिए, महाराजा जय सिंह ने विशाल पत्थर और चूने के विशाल खगोलीय यंत्र तैयार किए। इस परिसर का सबसे प्रमुख आकर्षण सम्राट यंत्र है, जो 27 मीटर ऊंची एक विशाल धूपघड़ी है। इसकी विशाल छाया संगमरमर के पैमानों पर पड़ती है, जिससे केवल 2 सेकंड की सटीकता के साथ स्थानीय समय मापा जा सकता है। इसके पास ही राम यंत्र स्थित है, जो बेलनाकार खंभों के रूप में बना है और आकाशीय पिंडों की ऊंचाई और दिशा मापने के काम आता था। जय प्रकाश यंत्र में दो धंसी हुई अर्धगोलाकार कटोरियाँ हैं, जिनके अंदर चलकर खगोलशास्त्री तारों और ग्रहों की स्थिति का सटीक अवलोकन करते थे। तीन सदियों बाद भी आधुनिक गगनचुंबी इमारतों के बीच खड़ा जंतर मंतर प्राचीन भारतीय विज्ञान, गणित और वास्तुकला की अद्वितीय प्रतिभा का जीवंत साक्ष्य है। आइए, इस वैज्ञानिक धरोहर की अद्भुत ज्यामिति और रहस्यों को करीब से जानिए।`
  },
  {
    slug: 'akshardham',
    en: `Welcome to Swaminarayan Akshardham, a magnificent spiritual and cultural sanctuary sprawling across one hundred acres along the banks of the Yamuna River in East Delhi. Inaugurated in November 2005 by Pramukh Swami Maharaj, this monumental complex honors ten thousand years of Indian art, spiritual wisdom, architecture, and values. The central Mandir, soaring forty-three meters into the sky, was built entirely without the use of structural steel or iron, adhering strictly to traditional Shilpa Shastra temple architecture. It was sculpted by seven thousand skilled master artisans from Rajasthani pink sandstone and pure white Italian Carrara marble. As you walk around the sanctum, examine the Gajendra Pith, a colossal stone elephant plinth comprising one hundred and forty-eight life-sized carved elephants paying homage to the sacred bond between nature and human life. The temple walls boast two hundred exquisitely sculpted stone spires and over twenty thousand intricately carved figures of deities, sages, and celestial beings. Inside the inner sanctum rests the eleven-foot gold-plated statue of Bhagwan Swaminarayan, surrounded by a peaceful spiritual ambiance. Beyond the Mandir, visitors can explore thematic exhibitions celebrating timeless moral values, a heritage boat ride depicting thousands of years of ancient Indian discoveries, and the Sahaj Anand musical fountain light show. Akshardham represents a sublime celebration of devotion, craftsmanship, and timeless Indian spiritual philosophy.`,
    hi: `पूर्वी दिल्ली में यमुना नदी के तट पर स्थित भव्य स्वामीनारायण अक्षरधाम मंदिर में आपका हार्दिक स्वागत है। नवंबर 2005 में पूज्य प्रमुख स्वामी महाराज द्वारा उद्घाटित यह विशाल परिसर भारतीय संस्कृति, आध्यात्मिकता, वास्तुकला और सनातन मूल्यों का एक अद्भुत संगम है। सौ एकड़ में फैला यह भव्य मंदिर प्राचीन शिल्पशास्त्र के नियमों के अनुसार बिना किसी लोहे या स्टील के केवल राजस्थानी गुलाबी बलुआ पत्थर और इटैलियन संगमरमर से तराशा गया है। इसे 7000 कुशल कारीगरों ने पाँच वर्षों की अथक साधना से तैयार किया। मुख्य मंदिर के चारों ओर गजेंद्र पीठ बना है, जिसमें 148 तराशे हुए आदमकद हाथी भारतीय संस्कृति में प्रकृति के महत्व को दर्शाते हैं। मंदिर के बाहरी और भीतरी भागों में 200 से अधिक नक्काशीदार शिखर और 20,000 से अधिक ऋषि-मुनियों और देवताओं की सुंदर मूर्तियाँ उकेरी गई हैं। गर्भगृह में भगवान स्वामीनारायण की 11 फीट ऊंची स्वर्ण-मंडित भव्य प्रतिमा सुशोभित है। मंदिर के अलावा यहाँ प्राचीन भारत के आविष्कारों को दर्शाने वाली नौका विहार, ज्ञानवर्धक प्रदर्शनियाँ और शाम को होने वाला संगीतमय फव्वारा शो दर्शकों को मंत्रमुग्ध कर देता है। आइए, इस पावन धाम की भव्यता और शांति का अनुभव कीजिए।`
  },
  {
    slug: 'safdarjung-tomb',
    en: `Welcome to the serene gardens of Safdarjung Tomb, the last great monumental garden tomb built during the twilight years of the Mughal Empire. Constructed in 1754 by Nawab Shuja-ud-Daula for his father, Mirza Muqim Abul Mansur Khan, famously known as Safdarjung, who served as the powerful Grand Vizier of the Mughal empire under Emperor Ahmad Shah Bahadur. Designed in the classical Charbagh paradise garden layout, the mausoleum sits elevated on a high podium surrounded by four lush quadrants bisected by reflective water channels and fountains. As you approach the central tomb, observe how its architecture reflects a late Mughal baroque aesthetic, built of buff and brownish-red sandstone adorned with white marble inlays. The central structure is crowned by a high bulbous white marble dome, flanked by four polygonal corner minarets surmounted by domed kiosks. Inside the high vaulted central chamber, beneath delicate plaster floral frescoes and arabesque plasterwork, lies the cenotaph of Safdarjung and his wife Amatuz Zohra, while the actual resting graves lie protected in an underground crypt. The monument also houses historic pavilions known as Jangli Mahal and Moti Mahal, which once accommodated family members and court guards. The peaceful setting and gentle birdsong make Safdarjung Tomb a tranquil haven that offers a poignant reflection on the final artistic chapter of the Mughal dynasty.`,
    hi: `सफ़दरजंग के मकबरे के इस शांत और सुरम्य प्रांगण में आपका स्वागत है। सन 1754 में नवाब शुजाउद्दौला द्वारा अपने पिता मिर्ज़ा मुकीम अबुल मंसूर ख़ान, जिन्हें नवाब सफ़दरजंग के नाम से जाना जाता था, की याद में यह मकबरा बनवाया गया था। सफ़दरजंग मुग़ल सम्राट अहमद शाह बहादुर के वज़ीर-ए-आज़म थे। यह मकबरा मुग़ल साम्राज्य के पतन के दौर का अंतिम महान चारबाग उद्यान मकबरा माना जाता है। एक ऊंचे चबूतरे पर स्थित यह मुख्य मकबरा चारों ओर से जल नहरों और फव्वारों वाले चार बागों से घिरा हुआ है। इसकी बनावट में लाल-भूरे बलुआ पत्थर और सफ़ेद संगमरमर का सुंदर प्रयोग किया गया है। मुख्य इमारत के ऊपर संगमरमर का एक विशाल गुंबद है और इसके चारों कोनों पर सुंदर छतरियों वाली मीनारें बनी हैं। मुख्य कक्ष के अंदर छत पर की गई बारीक प्लास्टर नक्काशी और मेहराबें अत्यंत दर्शनीय हैं। यहाँ नवाब सफ़दरजंग और उनकी बेगम की संगमरमर की समाधियाँ स्थित हैं, जबकि असली कब्रें भूमिगत तहखाने में सुरक्षित हैं। परिसर में मोती महल और जंगली महल नाम के सुंदर मंडप भी मौजूद हैं। हरियाली और पक्षियों की चहचहाहट के बीच, सफ़दरजंग का यह मकबरा मुग़ल कला के अंतिम सुनहरे अध्याय की गवाही देता है।`
  },
  {
    slug: 'lodhi-garden',
    en: `Welcome to Lodhi Garden, a ninety-acre historic botanical sanctuary in the heart of South Delhi that seamlessly blends 15th-century medieval sultanate architecture with verdant landscaped lawns. Originally constructed during the reigns of the Sayyid and Lodi dynasties, who ruled Delhi prior to the Mughal conquest, the park preserves magnificent royal tombs that represent an essential evolutionary bridge between Sultanate and Mughal styles. As you stroll along the paved walking avenues, the most imposing monument you encounter is the Bara Gumbad, or Big Dome, built in 1494 as a monumental gateway to an attached three-domed mosque adorned with exquisite incised plaster arabesques and Quranic calligraphic bands. Across the courtyard stands the Shisha Gumbad, or Glazed Dome, whose facade was once adorned with shimmering turquoise and cobalt blue ceramic tiles that mirrored the morning sun. Further south lies the striking octagonal tomb of Mohammed Shah of the Sayyid dynasty, surrounded by an open arcaded gallery with sloping stone eaves. To the north, the walled garden tomb of Sikandar Lodi, the founder of Agra, features the earliest surviving double dome in Delhi. Cross over the Athpula, a picturesque 16th-century arched stone bridge spanning an ornamental stream, and enjoy the tranquil sight of blooming roses, ancient neem and banyan trees, and singing parrots that make Lodhi Garden Delhi’s most cherished heritage sanctuary.`,
    hi: `दक्षिण दिल्ली के दिल में स्थित लोधी गार्डन के इस हरे-भरे और ऐतिहासिक पार्क में आपका स्वागत है। 90 एकड़ में फैला यह खूबसूरत उद्यान 15वीं शताब्दी के लोधी और सैयद राजवंशों के ऐतिहासिक स्मारकों और प्राकृतिक हरियाली का एक बेजोड़ संगम है। मुग़ल काल से पहले का यह इतिहास यहाँ के मकबरों की वास्तुकला में साफ झलकता है। पार्क के बीचों-बीच स्थित 'बड़ा गुंबद' सन 1494 में बनाया गया था, जो अपनी ऊंची गुंबदनुमा बनावट और साथ बनी मस्जिद की नक्काशीदार दीवारों के लिए प्रसिद्ध है। इसके ठीक सामने 'शीश गुंबद' खड़ा है, जिसकी दीवारों पर कभी नीली चमकदार टाइलें लगी थीं जो सूरज की रोशनी में चमकती थीं। थोड़ा आगे बढ़ने पर सैयद वंश के शासक मोहम्मद शाह का अष्टकोणीय मकबरा दिखाई देता है, जिसके चारों ओर खुली मेहराबदार दीर्घा बनी है। उत्तर दिशा में आगरा शहर के संस्थापक सिकंदर लोधी का मकबरा स्थित है, जिसमें दिल्ली का पहला दोहरा गुंबद देखने को मिलता है। 16वीं सदी का 'अठपुला' पुल, जो आठ खंभों पर टिका है, इस उद्यान की सुंदरता में चार चांद लगाता है। खूबसूरत फूलों, पुराने बरगद के पेड़ों और पक्षियों की मधुर आवाज़ों के बीच, लोधी गार्डन दिल्ली का सबसे पसंदीदा ऐतिहासिक और सुकून भरा ठिकाना है।`
  },
  {
    slug: 'sunder-nursery',
    en: `Welcome to Sunder Nursery, Delhi's celebrated heritage ecological wonderland spanning ninety tranquil acres adjacent to Humayun's Tomb in Nizamuddin. Originally established during the British era in 1913 as Azim Bagh to propagate plants for the construction of New Delhi, this site was transformed over an ambitious decade-long conservation masterplan led by the Aga Khan Trust for Culture in partnership with the Archaeological Survey of India. Today, Sunder Nursery harmoniously weaves together sixteen historical monuments, six of which are UNESCO World Heritage sites, with rich ecological habitats comprising over three hundred diverse tree species, thousands of blooming flowers, and fifty-four varieties of butterflies. As you walk along the grand central axial water canal, notice how the fountains gently cascade through sandstone channels modeled on classical Mughal paradise gardens. Among the key architectural treasures you will discover are the Sunder Burj, crowned by star-patterned plasterwork ceilings, the domed Lakkarwala Burj surrounded by rose gardens, and the elevated Mirza Muzaffar Husain Tomb. With tranquil lotus ponds, bird-watching sanctuaries, shaded amphitheaters, and weekend artisanal organic markets, Sunder Nursery stands as Delhi's premier historic urban sanctuary where conservation, biodiversity, and human relaxation flourish side by side.`,
    hi: `सुंदर नर्सरी के इस शांत और मनोरम हेरिटेज पार्क में आपका हार्दिक स्वागत है। 90 एकड़ में फैला यह खूबसूरत पार्क निज़ामुद्दीन में हुमायूँ के मकबरे के ठीक पास स्थित है। 16वीं शताब्दी में मुग़ल काल के दौरान इसे 'अज़ीम बाग़' के नाम से जाना जाता था, जिसे बाद में ब्रिटिश काल में नई दिल्ली के निर्माण के समय पौधों की नर्सरी बनाया गया। पिछले एक दशक में आगा खान ट्रस्ट फ़ॉर कल्चर और भारतीय पुरातत्व सर्वेक्षण के सहयोग से इसका कायाकल्प कर इसे एक विश्वस्तरीय हेरिटेज इकोलॉजिकल पार्क का रूप दिया गया। यहाँ 16 ऐतिहासिक मुग़ल स्मारक मौजूद हैं, जिनमें से छह यूनेस्को की विश्व धरोहर सूची में शामिल हैं। इसके अलावा यहाँ 300 से अधिक प्रकार के दुर्लभ पेड़-पौधे, सुंदर तितली पार्क और पक्षियों का बसेरा है। पार्क के बीचों-बीच बहती संगमरमर की जल नहरें और फव्वारे मुग़ल चारबाग शैली की याद दिलाते हैं। यहाँ का 'सुंदर बुर्ज' अपनी छत की नक्काशी के लिए और 'लक्कड़वाला बुर्ज' अपने चारों ओर खिले गुलाबों के लिए प्रसिद्ध है। शांत झीलें, चलने के सुंदर रास्ते और वीकेंड पर लगने वाले जैविक बाज़ार सुंदर नर्सरी को दिल्ली का सबसे आकर्षक और सुकून भरा स्थल बनाते हैं।`
  },
  {
    slug: 'hauz-khas-fort',
    en: `Welcome to the historic ruins of Hauz Khas Fort and its adjoining lakeside collegiate complex, where medieval Delhi Sultanate heritage meets vibrant contemporary urban culture. The story of Hauz Khas began in 1295 when Sultan Alauddin Khilji excavated a massive water reservoir known as Hauz-i-Alai, or the Royal Tank, to supply fresh drinking water to the nearby fortified city of Siri. Nearly five decades later, Sultan Feroz Shah Tughlaq desilted the tank and constructed an extraordinary L-shaped collegiate madrasa along its southern and eastern stone banks. Regarded as one of the premier Islamic educational centers of the medieval world, students and scholars gathered here from across Asia to study mathematics, theology, astronomy, and medicine in stone colonnaded classrooms overlooking the serene lake. At the corner where the two wings converge rises the square stone tomb of Feroz Shah Tughlaq, crowned by a smooth rubble-masonry dome and paved with a polished marble floor. Surrounding the madrasa are picturesque stone pavilions, cenotaphs of revered teachers, and an assembly hall where academic lectures were delivered. Today, as gentle breezes drift across the revived lake and through the ancient stone arches, Hauz Khas offers visitors a captivating journey back into the intellectual zenith of 14th-century Delhi.`,
    hi: `हौज़ खास किले और इसके ऐतिहासिक परिसर में आपका स्वागत है। यहाँ 14वीं शताब्दी का गौरवशाली इतिहास और आधुनिक संस्कृति एक साथ जीवंत होते हैं। इस ऐतिहासिक स्थल की शुरुआत सन 1295 में हुई थी, जब दिल्ली के सुल्तान अलाउद्दीन खिलजी ने अपने नए शहर सीरी के निवासियों के लिए पानी का एक विशाल तालाब खुदवाया, जिसे 'हौज़-ए-अलाई' कहा गया। लगभग पचास साल बाद सुल्तान फ़िरोज़ शाह तुग़लक ने इस तालाब की गाद साफ कराई और इसके किनारे एक विशाल एल-आकार के मदरसे का निर्माण कराया। यह मदरसा मध्यकालीन दुनिया के सबसे प्रमुख शिक्षा केंद्रों में से एक था, जहाँ दूर-दूर से छात्र गणित, खगोलशास्त्र, धर्म और चिकित्सा का अध्ययन करने आते थे। दोनों विंग्स के मिलन स्थल पर सुल्तान फ़िरोज़ शाह तुग़लक का भव्य मकबरा स्थित है, जो पत्थरों से बना एक सुंदर गुंबदनुमा स्मारक है। इसके चारों ओर बने खुले पत्थर के मंडप और मेहराबें तालाब के सुंदर दृश्यों को दिखाते हैं। आज भी इस ऐतिहासिक झील के किनारे बैठकर ठंडी हवा और प्राचीन पत्थरों के बीच इतिहास के उस सुनहरे दौर को महसूस किया जा सकता है।`
  },
  {
    slug: 'purana-qila',
    en: `Welcome to Purana Qila, or the Old Fort of Delhi, an ancient citadel standing on a legendary prehistoric mound associated with Indraprastha, the mythological capital of the Pandavas from the Mahabharata epic. Extensive archaeological excavations conducted by the Archaeological Survey of India have unearthed continuous cultural layers dating back over three thousand years to the Painted Grey Ware period. The towering stone ramparts you see today were constructed in the mid-16th century during the dramatic power struggle between Mughal Emperor Humayun and the Afghan visionary ruler Sher Shah Suri. Rising nearly twenty meters high, the fortress is entered through three imposing two-storied gateways flanked by massive bastions, including the Bada Darwaza and the Talaqi Darwaza. Inside the citadel stands the Qila-i-Kuhna Mosque, an architectural masterpiece built by Sher Shah Suri in 1541. Its striking facade combines red sandstone with white and black marble inlays, featuring horseshoe-shaped arches that heralded the arrival of Mughal architectural symmetry. Nearby rises the Sher Mandal, an octagonal two-story red sandstone pavilion originally built as an astronomical observatory and later utilized by Emperor Humayun as his royal library, from whose steep steps he tragically fell in 1556. With scenic boating along the historic moat, ancient stepwells, and evening sound and light spectacles, Purana Qila preserves Delhi's oldest living memories.`,
    hi: `दिल्ली के सबसे प्राचीन और रहस्यमयी किलों में से एक पुराना किला में आपका हार्दिक स्वागत है। मान्यता है कि यह किला उसी टीले पर स्थित है जहाँ महाभारत काल में पांडवों की भव्य राजधानी इंद्रप्रस्थ हुआ करती थी। पुरातत्व विभाग की खुदाइयों में यहाँ 3000 साल पुराने अवशेष मिले हैं जो इस मान्यता को बल देते हैं। आज जो भव्य लाल बलुआ पत्थर की दीवारें और बुर्ज आप देख रहे हैं, उनका निर्माण 16वीं सदी में मुग़ल सम्राट हुमायूँ और अफ़गान शासक शेरशाह सूरी के शासनकाल में हुआ था। किले के तीन विशाल द्वारों में 'बड़ा दरवाज़ा' और 'तलाकी दरवाज़ा' अत्यंत भव्य हैं। किले के भीतर शेरशाह सूरी द्वारा 1541 में बनवाई गई 'किला-ए-कुहना मस्जिद' मुग़ल पूर्व वास्तुकला का एक अनुपम उदाहरण है, जिसमें संगमरमर और बलुआ पत्थर का सुंदर काम किया गया है। इसके पास ही अष्टकोणीय 'शेर मंडल' स्थित है, जिसे हुमायूँ ने अपने पुस्तकालय के रूप में इस्तेमाल किया था और 1556 में इसी की सीढ़ियों से फिसलकर उनकी मृत्यु हो गई थी। किले के चारों ओर बनी झील में नौका विहार और शाम का लाइट एंड साउंड शो यहाँ के इतिहास को जीवंत कर देता है। आइए, दिल्ली की इस प्राचीनतम धरोहर का अन्वेषण कीजिए।`
  },
  {
    slug: 'rashtrapati-bhavan',
    en: `Welcome to Rashtrapati Bhavan, the official residence of the President of India, majestically situated atop Raisina Hill at the ceremonial western terminus of Kartavya Path. Completed in 1929 and designed by the eminent British architect Sir Edwin Lutyens with Sir Herbert Baker, this monumental palace represents one of the largest presidential residences in the democratic world, containing three hundred and forty stately rooms spread over four sprawling levels. The architecture brilliantly synthesizes classical European neoclassical symmetry with indigenous Indian architectural traditions, such as projecting stone chhatri kiosks, deep sunshade chhajja cornices, and perforated jaali stone screens. The estate is crowned by a colossal copper dome modeled on the ancient Buddhist Stupa of Sanchi. Inside lie the Durbar Hall, where momentous historical ceremonies take place beneath a two-ton chandelier, and the Ashoka Hall, celebrated for its exquisite Persian ceiling oil paintings. Sprawling behind the mansion is the world-renowned Amrit Udyan, formerly known as the Mughal Gardens, covering fifteen acres of manicured multi-tiered terraces. These gardens feature musical water fountains, circular sunburst gardens, and over one hundred and fifty rare varieties of blooming roses and exotic tulips. A visit to Rashtrapati Bhavan offers an extraordinary glimpse into the majesty of India's democratic heritage and living history.`,
    hi: `रायसीना हिल की ऊंचाई पर स्थित भारत के राष्ट्रपति के आधिकारिक निवास राष्ट्रपति भवन में आपका हार्दिक स्वागत है। कर्तव्य पथ के छोर पर स्थित यह भव्य महल दुनिया के सबसे बड़े लोकतंत्र के राष्ट्राध्यक्ष का निवास है। इसका निर्माण 1929 में प्रसिद्ध ब्रिटिश वास्तुकार सर एडविन लुटियंस और हर्बर्ट बेकर के निर्देशन में पूरा हुआ था। 340 कमरों वाली यह विशाल चार मंजिला इमारत शास्त्रीय पश्चिमी वास्तुकला और पारंपरिक भारतीय स्थापत्य कला जैसे छतरियों, जालियों और छज्जों का एक सुंदर संगम है। इसके शीर्ष पर बना विशाल तांबे का गुंबद सांची के प्राचीन बौद्ध स्तूप से प्रेरित है। इसके भीतर स्थित 'दरबार हॉल' और 'अशोक हॉल' अपनी भव्यता और छत पर बनी फ़ारसी पेंटिंग्स के लिए पूरी दुनिया में जाने जाते हैं। राष्ट्रपति भवन के पीछे 15 एकड़ में फैला 'अमृत उद्यान' स्थित है, जिसे पहले मुग़ल गार्डन कहा जाता था। यहाँ सीढ़ीदार बागीचों में 150 से अधिक दुर्लभ किस्मों के गुलाब, विदेशी ट्यूलिप और संगीतमय फव्वारे खिलते हैं जो हर साल लाखों पर्यटकों को आकर्षित करते हैं। आइए, भारत के इस गौरवशाली राष्ट्रीय प्रतीक की भव्यता का अनुभव कीजिए।`
  },
  {
    slug: 'chandni-chowk',
    en: `Welcome to Chandni Chowk, the legendary Moonlight Square of Old Delhi and one of the oldest, richest, and most vibrant heritage marketplaces in Asia. Commissioned in 1650 by Princess Jahanara Begum, the beloved daughter of Emperor Shah Jahan, this grand commercial boulevard once featured a wide central canal fed by the Yamuna River that reflected the shimmering moonlight, giving the market its poetic name. Historically, wealthy merchants and royal traders from Turkey, Persia, China, and across India gathered here to trade rare emeralds, rubies, fine brocades, perfumes, and spices. Today, stretching westward from the Lahore Gate of the Red Fort to the historic Fatehpuri Masjid, Chandni Chowk has been revitalized with a pedestrian-only granite promenade adorned with heritage lampposts and green median strips. Branching off the main spine are legendary specialized historic alleys: Dariba Kalan, renowned for handcrafted silver jewellery and natural ittar fragrances; the Khari Baoli spice market, the largest wholesale spice bazaar in all of Asia, filling the air with aromas of cardamom, saffron, and cloves; and the iconic Paranthe Wali Gali, serving sizzling stuffed flatbreads since the 1870s. Brimming with centuries of continuous trade, vibrant spirituality, and irresistible culinary aromas, Chandni Chowk is the indomitable living soul of Old Delhi.`,
    hi: `पुरानी दिल्ली के ऐतिहासिक और मशहूर बाज़ार चांदनी चौक में आपका हार्दिक स्वागत है। सन 1650 में सम्राट शाहजहाँ की विदुषी पुत्री राजकुमारी जहाँआरा द्वारा डिज़ाइन किया गया यह बाज़ार कभी चाँद की रोशनी में चमकने वाली एक सुंदर नहर के लिए जाना जाता था, जिससे इसका नाम 'चांदनी चौक' पड़ा। पुराने ज़माने में यहाँ दुनिया भर के व्यापारी रेशम, इत्र, मसाले और कीमती जवाहरात बेचने आते थे। लाल किले के लाहौरी गेट से लेकर ऐतिहासिक फ़तेहपुरी मस्जिद तक फैला यह बाज़ार आज भी पुरानी दिल्ली की धड़कन है। हाल ही में इसका पुनरुद्धार कर इसे एक सुंदर पैदल मार्ग में बदल दिया गया है। चांदनी चौक की तंग गलियों में इतिहास और स्वाद का अद्भुत संगम है। दरीबा कलां अपने पुश्तैनी चांदी के आभूषणों और असली इत्र के लिए मशहूर है; खारी बावली एशिया का सबसे बड़ा मसालों का थोक बाज़ार है, जहाँ इलायची, केसर और लौंग की महक हवा में घुली रहती है; और मशहूर 'पराठे वाली गली' में 1870 के दशक से पारंपरिक पराठे तले जा रहे हैं। अपनी समृद्ध विरासत, अनूठे बाज़ारों और लज़ीज़ पकवानों के साथ चांदनी चौक हिंदुस्तान की जीवंत तहज़ीब का आईना है।`
  }
];

async function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

async function generateFileWithRetry(text, filepath, voice, lang, maxRetries = 3) {
  if (fs.existsSync(filepath) && fs.statSync(filepath).size > 100000) {
    console.log(`⚡ Skipping (Already exists & valid): ${path.basename(filepath)} (${fs.statSync(filepath).size} bytes)`);
    return true;
  }

  for (let attempt = 1; attempt <= maxRetries; attempt++) {
    try {
      console.log(`[Attempt ${attempt}/${maxRetries}] Generating ${path.basename(filepath)} with ${voice}...`);
      const tts = new EdgeTTS({
        voice,
        lang,
        timeout: 90000
      });
      await tts.ttsPromise(text, filepath);
      const size = fs.existsSync(filepath) ? fs.statSync(filepath).size : 0;
      if (size > 10000) {
        console.log(`✓ Successfully generated: ${path.basename(filepath)} (${size} bytes)`);
        await sleep(1500);
        return true;
      }
    } catch (err) {
      console.warn(`Warning on attempt ${attempt} for ${path.basename(filepath)}:`, err.message || err);
      await sleep(3000);
    }
  }
  console.error(`❌ All attempts failed for ${path.basename(filepath)}`);
  return false;
}

async function generateAll() {
  console.log('--- Starting Audio Generation for Remaining 10 Delhi Landmarks ---');
  
  for (const item of remainingScripts) {
    // English
    const enFile = path.join(outputDir, `${item.slug}-en.mp3`);
    await generateFileWithRetry(item.en, enFile, EN_VOICE, 'en-IN');

    // Hindi
    const hiFile = path.join(outputDir, `${item.slug}-hi.mp3`);
    await generateFileWithRetry(item.hi, hiFile, HI_VOICE, 'hi-IN');
  }

  console.log('--- All 10 Remaining Landmarks Audio Files Generated Successfully! ---');
}

generateAll().catch(console.error);
